<?php

/**
 * @file
 * Custom ctools module
 */

/**
 * Implements hook_menu().
 */
function custom_ctools_menu() {
  $items['custom-ctools/%ctools_js/form'] = array(
    'title' => 'My custom ctools form page',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'page callback' => 'custom_ctools_callback_form',
    'type' => MENU_CALLBACK,
  );
  $items['custom-ctools/%ctools_js/multistep-form'] = array(
    'title' => 'My custom ctools multistep form page',
    'page callback' => 'custom_ctools_callback_multistep_form',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['custom-ctools/%ctools_js/webform/%'] = array(
    'title' => 'My custom ctools webform page',
    'page callback' => 'custom_ctools_callback_webform',
    'page arguments' => array(1,3),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['custom-ctools'] = array(
    'title' => 'My custom ctools page',
    'access callback' => TRUE,
    'page callback' => 'custom_ctools_page',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Custom ctools popup's form.
 */
function custom_ctools_form($form, $form_state) {
  $form = array();
  $form['some_text'] = array(
    '#title' => t('Some text'),
    '#type' => 'textfield',
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  return $form;
}

/**
 * Page callback: custom form html.
 *
 * @see custom_ctools_menu()
 */
function custom_ctools_callback_form($js = NULL) {
  if (!$js) {
    return drupal_get_form('custom_ctools_form');
  }
  ctools_include('ajax');
  ctools_include('modal');
  $form_state = array(
    'ajax' => TRUE,
    'title' => t('Custom form title'),
  );
  $output = ctools_modal_form_wrapper('custom_ctools_form', $form_state);
  print ajax_render($output);
  drupal_exit();
}

/**
 * Page callback: Handles multistep precessing.
 *
 * @return string
 *   Multistep wizard output.
 *
 * @see custom_ctools_menu()
 */
function custom_ctools_callback_multistep_form($js = NULL, $step = NULL) {
  if ($js) {
    ctools_include('modal');
    ctools_include('ajax');
  }

  // Define array for ctools multistep wizard.
  $form_info = array(
    'id' => 'custom-ctools',
    'path' => "custom-ctools/" . ($js ? 'ajax' : 'nojs') . "/multistep-form/%step",
    'show trail' => TRUE,//show or hide forms order
    'show back' => TRUE,
    'show cancel' => TRUE,
    'show return' => FALSE,
    'next callback' => 'custom_ctools_wizard_next',
    'finish callback' => 'custom_ctools_wizard_finish',
    'cancel callback' => 'custom_ctools_wizard_cancel',

    // Define forms order.
    'order' => array(
      'start' => t('Enter your info'),
      'second' => t('What do you know?'),
      'third' => t('What do think about drupal?'),
      'fourth' => t('Do you like cookies?'),
    ),

    // Define forms
    'forms' => array(
      'start' => array(
        'form id' => 'custom_ctools_form_start'
      ),
      'second' => array(
        'form id' => 'custom_ctools_form_second'
      ),
      'third' => array(
        'form id' => 'custom_ctools_form_third'
      ),
      'fourth' => array(
        'form id' => 'custom_ctools_form_fourth'
      ),
    ),
  );

  // We're not using any real storage here, so we're going to set our
  // object_id to 1. When using wizard forms, id management turns
  // out to be one of the hardest parts. Editing an object with an id
  // is easy, but new objects don't usually have ids until somewhere
  // in creation.
  //
  // We skip all this here by just using an id of 1.
  $object_id = 1;

  if (empty($step)) {

    // We reset the form when $step is NULL because that means they have
    // for whatever reason started over.
    custom_ctools_cache_clear($object_id);
    $step = 'start';
  }

  // This automatically gets defaults if there wasn't anything saved.
  $object = custom_ctools_cache_get($object_id);

  // live $form_state changes.
  $form_state = array(
    'ajax' => $js,

    // Put our object and ID into the form state cache so we can easily find it.
    'object_id' => $object_id,
    'object' => &$object,
  );

  // Send this all off to our form. This is like drupal_get_form only wizardy.
  ctools_include('wizard');
  $form = ctools_wizard_multistep_form($form_info, $step, $form_state);
  $output = drupal_render($form);
  if ($js) {

    // If javascript is active, we have to use a render array.
    $commands = array();
    if ($output === FALSE || !empty($form_state['complete'])) {
      // Dismiss the modal.
      $commands[] = ajax_command_html('#custom-ctools-multistep-results', render(custom_ctools_get_result($object)));
      $commands[] = ctools_modal_command_dismiss();
    }
    elseif (!empty($form_state['cancel'])) {

      // If cancelling, return to the activity.
      $commands[] = ctools_modal_command_dismiss();
    }
    else {
      $commands = ctools_modal_form_render($form_state, $output);
    }
    print ajax_render($commands);
  }
  else {
    if ($output === FALSE || !empty($form_state['complete'])) {

      return render(custom_ctools_get_result($object)) . "\n\r" . l(t('Back'), 'custom-ctools');
    }
    elseif (!empty($form_state['cancel'])) {
      drupal_goto('custom-ctools');
    }
    else {
      return $output;
    }
  }
}

/**
 * Page callback: html.
 *
 * @see custom_ctools_menu()
 */
function custom_ctools_callback_webform($js = NULL, $webform_nid) {
  $output = array();
  $webform_nid = (int)$webform_nid;
  $webform_node = node_load($webform_nid);
  if ($webform_node && $webform_node->type == 'webform') {
    if (!$js) {
      return drupal_get_form('webform_client_form_'.$webform_nid, $webform_node, FALSE);
    }
    ctools_include('ajax');
    ctools_include('modal');
    // show full node
    // $webfrom_view = node_view($webform_node);
    // $webform = drupal_render($webfrom_view);
    // show only form
    $webform_form = drupal_get_form('webform_client_form_'.$webform_nid, $webform_node, FALSE);
    $webform = drupal_render($webform_form);
    $output[] = ctools_modal_command_display(t($webform_node->title), $webform);
  } else {
    $popup_content = t('Webform not found. Please check your link.');
    if (!$js) {
      return $popup_content;
    }
    ctools_include('ajax');
    ctools_include('modal');
    $output[] = ctools_modal_command_display(t('Webform not found'), $popup_content);
  }
  print ajax_render($output);
  drupal_exit();
}

/**
 * Page callback: Dispalys custom ctools links.
 *
 * @return array
 *   A render array for displaying few links.
 *
 * @see custom_ctools_menu()
 */
function custom_ctools_page() {
  custom_ctools_popup_style();
  $links = array();
  // The extra class points to the info in custom-ctools-popup-style which we added
  // to the settings, prefixed with 'ctools-modal'.
  $links[] = ctools_modal_text_button(t('Form modal'), 'custom-ctools/nojs/form', t('Custom ctools modal form'), 'ctools-modal-custom-ctools-popup-style');
  $links[] = ctools_modal_text_button(t('Webform modal'), 'custom-ctools/nojs/webform/7', t('Custom ctools modal webform'), 'ctools-modal-custom-ctools-popup-style');
  $links[] = l(t('Multistep form nojs'), 'custom-ctools/nojs/multistep-form');
  $links[] = ctools_modal_text_button(t('Multistep from modal'), 'custom-ctools/nojs/multistep-form', t('Start'), 'ctools-modal-custom-ctools-popup-style');
  $links[] = '<div id="custom-ctools-multistep-results">' . t('Here will come result in modal case') . '</div>';
  return  array('#theme' => 'item_list', '#items' => $links);
}

/**
 * Clears the wizard cache.
 *
 * @param integer $id
 *   cache id.
 */
function custom_ctools_cache_clear($id) {
  ctools_include('object-cache');
  ctools_object_cache_clear('custom_ctools', $id);
}

/**
 * Stores our little cache so that we can retain data from form to form.
 *
 * @param integer $id
 *   cache id.
 * @param object $object
 *   object with form values.
 */
function custom_ctools_cache_set($id, $object) {
  ctools_include('object-cache');
  ctools_object_cache_set('custom_ctools', $id, $object);
}

/**
 * Gets the current object from the cache, or default.
 *
 * @param integer $id
 *   cache id.
 *
 * @return object
 *   cache with stored stuff.
 */
function custom_ctools_cache_get($id) {
  ctools_include('object-cache');
  $object = ctools_object_cache_get('custom_ctools', $id);
  if (!$object) {
    // Create a default object.
    $object = new stdClass;
  }
  return $object;
}

/**
 * Handles the 'next' click on the add/edit pane form wizard.
 *
 * All we need to do is store the updated pane in the cache.
 */
function custom_ctools_wizard_next(&$form_state) {
  custom_ctools_cache_set($form_state['object_id'], $form_state['object']);
}

/**
 * Handles the 'finish' click on teh add/edit pane form wizard.
 *
 * All we need to do is set a flag so the return can handle adding
 * the pane.
 */
function custom_ctools_wizard_finish(&$form_state) {
  $form_state['complete'] = TRUE;
}

/**
 * Handles the 'cancel' click on the add/edit pane form wizard.
 */
function custom_ctools_wizard_cancel(&$form_state) {
  $form_state['cancel'] = TRUE;
}

/**
 * Generates first form.
 *
 * @ingroup forms
 */
function custom_ctools_form_start($form, &$form_state) {
  $form_state['title'] = t('Enter your info');//change title modal popup
  $form['name'] = array(
    '#type'          => 'textfield',
    '#title'         => t('First name'),
    '#default_value' => isset($form_state['object']->name) ? $form_state['object']->name : '',
    '#required'      => TRUE,
  );
  $form['surname'] = array(
    '#type' => 'textfield',
    '#title' => t('Last name'),
    '#default_value' => isset($form_state['object']->surname) ? $form_state['object']->surname : '',
    '#required' => TRUE,
  );
  return $form;
}

/**
 * Handles submit of first form.
 */
function custom_ctools_form_start_submit($form, &$form_state) {
  $form_state['object']->name = $form_state['values']['name'];
  $form_state['object']->surname = $form_state['values']['surname'];
}

/**
 * Generates second form.
 *
 * @ingroup forms
 */
function custom_ctools_form_second($form, &$form_state) {
  $form_state['title'] = t('What do you know?');//change title modal popup
  $form['know'] = array(
    '#type'          => 'checkboxes',
    '#options'       => array('php' => t('PHP'), 'css' => t('CSS'), 'jquery' => t('Jquery'), 'unix' => t('Unix')),
    '#default_value' => isset($form_state['object']->know) ? $form_state['object']->know : array(),
  );
  return $form;
}

/**
 * Handles submit for second form.
 */
function custom_ctools_form_second_submit($form, &$form_state) {
  $form_state['object']->know = $form_state['values']['know'];
}

/**
 * Generates third form.
 *
 * @ingroup forms
 */
function custom_ctools_form_third($form, &$form_state) {
  $form_state['title'] = t('What do think about drupal?');//change title modal popup
  $form['drupal'] = array(
    '#type'          => 'radios',
    '#options'       => array('awesome' => t('Awesome'), 'awful' => t('Awful')),
    '#default_value' => isset($form_state['object']->drupal) ? $form_state['object']->drupal : '',
    '#default_value' => 'awesome',
    '#required'      => TRUE,
  );
  return $form;
}

/**
 * Handles submit for third form.
 */
function custom_ctools_form_third_submit(&$form, &$form_state) {
  $form_state['object']->drupal = $form_state['values']['drupal'];
}

/**
 * Generates fourth form.
 *
 * @ingroup forms
 */
function custom_ctools_form_fourth($form, &$form_state) {
  $form_state['title'] = t('Do you like cookies?');//change title modal popup
  $form['work'] = array(
    '#type'          => 'radios',
    '#options'       => array('yes' => t('Yes'), 'no' => t('No')),
    '#default_value' => 'yes',
    '#required'      => TRUE,
  );
  return $form;
}

/**
 * Handles submit for fourth form.
 */
function custom_ctools_form_fourth_submit(&$form, &$form_state) {
  $form_state['object']->work = $form_state['values']['work'];
}

/**
 * Returns form results.
 *
 * @param object $object
 *   object with form values.
 *
 * @return array
 *   returns renderable array for multistep form result output.
 */
function custom_ctools_get_result($object) {
  $out = array();
  $out[] = t('Your name: @name', array('@name' => $object->name));
  $out[] = t('Your surname: @surname', array('@surname' => $object->surname));
  $known = array_filter($object->know);
  if (count($known)) {
    $out[] = t('Your know: !know', array('!know' => implode(', ', $known)));
  }
  else {
    $out[] = t("You don't know anything");
  }
  $out[] = t('You think drupal is !mind', array('!mind' => $object->drupal));
  if ($object->work == 'yes') {
    $out[] = t('You like cookies :)');
  }
  else {
    $out[] = t("You don't like cookies :(");
  }
  return array('#theme' => 'item_list', '#items' => $out, '#title' => t('Results:'));
}

/**
 *Popup’s setings function.
 */
function custom_ctools_popup_style() {
  static $added = FALSE;
  if ($added == FALSE) {
    $added = TRUE;
    ctools_include('modal');
    ctools_include('ajax');
    ctools_modal_add_js();
    $popup_style = array(
      'custom-ctools-popup-style' => array(
        'modalSize' => array(
          'type' => 'fixed',
          'width' => 650,
          'height' => 'auto',
          /*'height' => 300,*/
          'addWidth' => 10,
          'addHeight' => 10,
        ),
        'modalOptions' => array(
          'opacity' => (float) 0.8,
          'background-color' => '#000',
        ),
        'closeText' => 'Close window',
        'loadingText' => '',
        'animation' => 'fadeIn',
        'modalTheme' => 'custom_ctools_popup_theme',
        'animationSpeed' => 'fast',
        'throbber' => theme('image', array('path' => ctools_image_path('ajax-loader.gif', 'custom_ctools'), 'alt' => t('Loading...'), 'title' => t('Loading'))),
      ),
    );
    drupal_add_js($popup_style, 'setting');
    ctools_add_js('custom_ctools_popup_style', 'custom_ctools');
    ctools_add_css('custom_ctools_popup_style', 'custom_ctools');
  }
}